[info]
name = "nnn"
version = "3.2"
url = "https://github.com/jarun/nnn"

[discover]
binary = "nnn"
version_check.args = ["-V"]
version_check.pattern = "(?m)^(.+)$"

[[install]]
download = "https://github.com/jarun/nnn/releases/download/v3.2/nnn-static-3.2.x86-64.tar.gz"
checksums.b2 = "8d3c036fab2747012bdfa781792b23e164419dc909e5e34d5904f1dac65fb3f5a18552171288758d7d93244720dee9fe2ec7bfce2972273ba7ce3eb87eb9a467"
files = [
    { source = "nnn-static", type = "bin", name = "nnn" },
]

[[install]]
download = "https://github.com/jarun/nnn/releases/download/v3.2/nnn-v3.2.tar.gz"
checksums.b2 = "1d5cb823d274e0ca8d15be75a6df149697d81abd5c60a4b7c6335317d77f5a071b917e3322b618924ad792defe3333d38e58fda0195bc0ed79bf72df371171b5"
files = [
    { source = "nnn-3.2/nnn.1", type = "man", section = 1 }
]
