name: "Test & Lint"

on:
  push:
    # Don't run CI for tags; there's always a branch for the tag as well so
    # there's no point in testing it separately
    tags_ignore: '*'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: rustfmt --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      - name: clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta]
    steps:
      - uses: actions/checkout@v2
      # Install musl tools for musl target
      - name: Install musl tools
        run: sudo apt-get install musl-tools
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          target: x86_64-unknown-linux-musl
      - name:
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --target x86_64-unknown-linux-musl
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target x86_64-unknown-linux-musl

  artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Install musl tools for musl target
      - name: Install musl tools
        run: sudo apt-get install musl-tools
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-musl
      - name: Build release binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-unknown-linux-musl
      - name: Strip binary
        run: strip 'target/x86_64-unknown-linux-musl/release/homebins'
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: "homebins"
          path: target/x86_64-unknown-linux-musl/release/homebins
